version: '3.9'

services:

  postgres:
    image: postgres:latest
    container_name: superbodega_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superbodega_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: superbodega_rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: SuperBodega.API/Dockerfile

    container_name: superbodega_api

    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data: