version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: SuperBodega.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=zephyr.proxy.rlwy.net;Port=13390;Database=railway;Username=postgres;Password=hqbjYSWpeNVlbgaMvveMlltLCRfftIFn
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - rabbitmq

  web:
    build:
      context: .
      dockerfile: SuperBodega.Web/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - api